In [ ]:
# Loan Approval Classification Dataset
# https://www.kaggle.com/datasets/taweilo/loan-approval-classification-data

# Loan Approval Classification Dataset

In [1]:
from credit_risk_lab.infrastructure.data_sources import CSVDatasetRepository

csv_repo = CSVDatasetRepository(
    name_file="loan_data.csv",
    name_folder="raw"
)
df = csv_repo.load()

df.head()

2025-11-30 10:22:13 | INFO     | CSVDatasetRepository | credit_risk_lab.infrastructure.data_sources.csv_dataset_repository:load:61 - Chargement du fichier : /Users/surelmanda/Downloads/ml-projects/credit-risk-lab/data/raw/loan_data.csv
2025-11-30 10:22:14 | INFO     | CSVDatasetRepository | credit_risk_lab.infrastructure.data_sources.csv_dataset_repository:load:72 - Dataset chargé (45000 lignes, 14 colonnes)

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

In [3]:
from credit_risk_lab.application import SplitDatasetUseCase
from credit_risk_lab.infrastructure.data_sources import CSVDatasetRepository


csv_repo = CSVDatasetRepository(name_file="loan_data.csv",name_folder="raw")
split_uc = SplitDatasetUseCase(dataset_repo=csv_repo)
train_df, test_df = split_uc.execute(test_size=0.2, random_state=42, save=True)

2025-11-30 10:23:50 | INFO     | SplitDatasetUseCase | credit_risk_lab.application.split_dataset_uc:execute:28 - Loading dataset via DatasetRepositoryPort...
2025-11-30 10:23:50 | INFO     | CSVDatasetRepository | credit_risk_lab.infrastructure.data_sources.csv_dataset_repository:load:61 - Chargement du fichier : /Users/surelmanda/Downloads/ml-projects/credit-risk-lab/data/raw/loan_data.csv
2025-11-30 10:23:50 | INFO     | CSVDatasetRepository | credit_risk_lab.infrastructure.data_sources.csv_dataset_repository:load:72 - Dataset chargé (45000 lignes, 14 colonnes)
2025-11-30 10:23:50 | INFO     | SplitDatasetUseCase | credit_risk_lab.application.split_dataset_uc:execute:30 - Dataset loaded successfully.
2025-11-30 10:23:50 | INFO     | SplitDatasetUseCase | credit_risk_lab.application.split_dataset_uc:execute:35 - Splitting dataset: test_size=0.2, random_state=42, target_column=loan_status
2025-11-30 10:23:50 | INFO     | SplitDatasetUseCase | credit_risk_lab.application.split_dataset_uc:execute:48 - Split completed: train=(36000, 14), test=(9000, 14)
2025-11-30 10:23:50 | INFO     | SplitDatasetUseCase | credit_risk_lab.application.split_dataset_uc:execute:56 - Saving split datasets via DatasetRepositoryPort...
2025-11-30 10:23:50 | INFO     | CSVDatasetRepository | credit_risk_lab.infrastructure.data_sources.csv_dataset_repository:save:84 - Sauvegarde du fichier : /Users/surelmanda/Downloads/ml-projects/credit-risk-lab/data/processed/train.csv
2025-11-30 10:23:50 | INFO     | CSVDatasetRepository | credit_risk_lab.infrastructure.data_sources.csv_dataset_repository:save:96 - Fichier sauvegardé avec succès ...
2025-11-30 10:23:50 | INFO     | CSVDatasetRepository | credit_risk_lab.infrastructure.data_sources.csv_dataset_repository:save:84 - Sauvegarde du fichier : /Users/surelmanda/Downloads/ml-projects/credit-risk-lab/data/processed/test.csv
2025-11-30 10:23:50 | INFO     | CSVDatasetRepository | credit_risk_lab.infrastructure.data_sources.csv_dataset_repository:save:96 - Fichier sauvegardé avec succès ...
2025-11-30 10:23:50 | INFO     | SplitDatasetUseCase | credit_risk_lab.application.split_dataset_uc:execute:59 - Datasets successfully saved to processed directory.

In [4]:
from credit_risk_lab.infrastructure.analytics import DataAnalyzer, DriftAnalyzer
from credit_risk_lab.infrastructure.data_sources import CSVDatasetRepository

csv_repo = CSVDatasetRepository(
    name_file="loan_data.csv",
    name_folder="raw"
)
df = csv_repo.load()

analyzer = DataAnalyzer(df)
summary = analyzer.summarize_dataset(max_examples=5)
display(summary)


numeric_cols, categorical_cols = analyzer.identify_feature_types()
print("Numériques :", numeric_cols[:10])
print("Catégorielles :", categorical_cols[:10])

2025-11-30 10:23:56 | INFO     | CSVDatasetRepository | credit_risk_lab.infrastructure.data_sources.csv_dataset_repository:load:61 - Chargement du fichier : /Users/surelmanda/Downloads/ml-projects/credit-risk-lab/data/raw/loan_data.csv
2025-11-30 10:23:56 | INFO     | CSVDatasetRepository | credit_risk_lab.infrastructure.data_sources.csv_dataset_repository:load:72 - Dataset chargé (45000 lignes, 14 colonnes)
2025-11-30 10:23:56 | INFO     | data_analyzer | credit_risk_lab.infrastructure.analytics.data_analysis:summarize_dataset:36 - Génération du résumé du dataset...
2025-11-30 10:23:56 | INFO     | data_analyzer | credit_risk_lab.infrastructure.analytics.data_analysis:summarize_dataset:68 - Résumé terminé : 14 colonnes, 45000 lignes.

,Column,Type,Missing,% Missing,Cardinality,Examples
0,person_age,float64,0,0.0,60,"[21.0, 22.0, 23.0, 24.0, 25.0]"
1,person_gender,object,0,0.0,2,"[female, male]"
2,person_education,object,0,0.0,5,"[Master, High School, Bachelor, Associate, Doc..."
3,person_income,float64,0,0.0,33989,"[12282.0, 12438.0, 66135.0, 71948.0, 79753.0]"
4,person_emp_exp,int64,0,0.0,63,"[0, 1, 3, 4, 5]"
5,person_home_ownership,object,0,0.0,4,"[RENT, OWN, MORTGAGE, OTHER]"
6,loan_amnt,float64,0,0.0,4483,"[1000.0, 1600.0, 2500.0, 5500.0, 35000.0]"
7,loan_intent,object,0,0.0,6,"[PERSONAL, EDUCATION, MEDICAL, VENTURE, HOMEIM..."
8,loan_int_rate,float64,0,0.0,1302,"[11.14, 12.87, 14.27, 15.23, 16.02]"
9,loan_percent_income,float64,0,0.0,64,"[0.08, 0.19, 0.44, 0.49, 0.53]"
10,cb_person_cred_hist_length,float64,0,0.0,29,"[2.0, 3.0, 4.0, 7.0, 8.0]"
11,credit_score,int64,0,0.0,340,"[504, 561, 586, 635, 675]"
12,previous_loan_defaults_on_file,object,0,0.0,2,"[No, Yes]"
13,loan_status,int64,0,0.0,2,"[0, 1]"

2025-11-30 10:23:56 | INFO     | data_analyzer | credit_risk_lab.infrastructure.analytics.data_analysis:identify_feature_types:96 - Identification des types de variables terminée.
2025-11-30 10:23:56 | INFO     | data_analyzer | credit_risk_lab.infrastructure.analytics.data_analysis:identify_feature_types:97 - Numériques (9): ['person_age', 'person_income', 'person_emp_exp', 'loan_amnt', 'loan_int_rate'] ...
2025-11-30 10:23:56 | INFO     | data_analyzer | credit_risk_lab.infrastructure.analytics.data_analysis:identify_feature_types:100 - Catégorielles (5): ['person_gender', 'person_education', 'person_home_ownership', 'loan_intent', 'previous_loan_defaults_on_file']
Numériques : ['person_age', 'person_income', 'person_emp_exp', 'loan_amnt', 'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length', 'credit_score', 'loan_status']
Catégorielles : ['person_gender', 'person_education', 'person_home_ownership', 'loan_intent', 'previous_loan_defaults_on_file']

In [5]:
analyzer.plot_target_distribution(target_col="loan_status")

2025-11-30 10:24:17 | INFO     | data_analyzer | credit_risk_lab.infrastructure.analytics.data_analysis:plot_target_distribution:201 - Visualisation complète affichée pour la cible 'loan_status'.

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_age                      45000 non-null  float64
 1   person_gender                   45000 non-null  object
 2   person_education                45000 non-null  object
 3   person_income                   45000 non-null  float64
 4   person_emp_exp                  45000 non-null  int64
 5   person_home_ownership           45000 non-null  object
 6   loan_amnt                       45000 non-null  float64
 7   loan_intent                     45000 non-null  object
 8   loan_int_rate                   45000 non-null  float64
 9   loan_percent_income             45000 non-null  float64
 10  cb_person_cred_hist_length      45000 non-null  float64
 11  credit_score                    45000 non-null  int64
 12  previous_loan_defaults_on_file  45000 non-null  object
 13  loan_status                     45000 non-null  int64
dtypes: float64(6), int64(3), object(5)
memory usage: 4.8+ MB

In [ ]:
"""
==============================================================
📘 METRIQUES DE CLASSIFICATION POUR CATBOOST & XGBOOST
==============================================================

Les modèles de gradient boosting (CatBoost / XGBoost) permettent 
d’utiliser un large éventail de métriques pour monitorer 
l’apprentissage (`eval_metric`) et optimiser la performance 
sur les dataset équilibrés ou déséquilibrés.

Ci-dessous : les métriques les plus fiables, leurs définitions 
et quand les utiliser.

--------------------------------------------------------------
1️⃣ METRIQUES CLASSIQUES
--------------------------------------------------------------
✔ Accuracy ("Accuracy")
   - Score simple : proportion correcte de prédictions.
   - À éviter sur un dataset déséquilibré.
   (Ex : 90% négatifs → accuracy = 90% même sans apprendre.)

✔ Precision ("Precision")
   - Importance quand faux positifs = coûteux.
   - Exemple : accepter de bons clients uniquement.

✔ Recall ("Recall")
   - Importance quand faux négatifs = très graves.
   - Exemple : détecter les clients risqués → scoring crédit.

✔ F1 Score ("F1")
   - Compromis précision / recall.
   - Recommandé sur dataset déséquilibrés.

✔ Balanced Accuracy ("BalancedAccuracy")
   - Moyenne du recall par classe.
   - Indispensable si dataset déséquilibré.

--------------------------------------------------------------
2️⃣ METRIQUES ROBUSTES POUR DATASET DÉSÉQUILIBRÉ
--------------------------------------------------------------
✔ AUC ("AUC")
   - Standard industriel en scoring (banque, assurance).
   - Indépendant du seuil de décision.
   - Excellent pour datasets déséquilibrés.

✔ PRAUC ("PRAUC")
   - AUC de la courbe Precision-Recall.
   - Encore meilleur que AUC si classe minoritaire très faible.

✔ MCC ("MCC")
   - “Matthews Correlation Coefficient”.
   - La meilleure métrique globale sur dataset déséquilibré.
   - Symétrique : punit vraiment les erreurs.

✔ Kappa ("Kappa")
   - Mesure la qualité du modèle vs. hasard.
   - Utile si dataset très déséquilibré.

✔ Normalized Gini ("NormalizedGini") — CatBoost uniquement
   - Très utilisé en modélisation de risque crédit.
   - Equivaut à 2*AUC - 1.

--------------------------------------------------------------
3️⃣ METRIQUES LIÉES À LA PROBABILITÉ
--------------------------------------------------------------
✔ LogLoss ("Logloss") ou CrossEntropy
   - Mesure la qualité des probabilités prédites.
   - Indispensable pour calibration.

✔ Brier Score ("BrierScore")
   - Mesure la précision de la probabilité estimée.

--------------------------------------------------------------
4️⃣ QUELLE METRIC UTILISER SELON LE CONTEXTE ?
--------------------------------------------------------------
➡ Dataset équilibré :
   - Accuracy, F1, AUC

➡ Dataset modérément déséquilibré :
   - AUC, F1, BalancedAccuracy

➡ Dataset fortement déséquilibré :
   - MCC (recommandé)
   - PRAUC
   - Recall (si FN graves)
   - NormalizedGini (banque / assurance)

➡ Scoring crédit :
   - AUC
   - NormalizedGini
   - LogLoss

--------------------------------------------------------------
5️⃣ CONSEIL PRATIQUE
--------------------------------------------------------------
• CatBoost accepte n’importe quel nom de metric : "AUC", "F1", 
  "BalancedAccuracy", "Kappa", etc.

• XGBoost accepte les metrics suivantes : "logloss", "auc", 
  "aucpr", "error", "map", "ndcg", "merror", "mlogloss", etc.

• Avec les datasets déséquilibrés, évite Accuracy.
  Préfère : AUC, F1, MCC ou BalancedAccuracy.

--------------------------------------------------------------
6️⃣ RECOMMANDATION PAR DÉFAUT
--------------------------------------------------------------
Pour un dataset déséquilibré (comme le tien) :
    eval_metric = "AUC"
ou :
    eval_metric = "MCC"     (si FN & FP très importants)

==============================================================
"""